//types

//user login + register
export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = 'USER_REGISTER'
export const SET_AUTH = 'SET_AUTH'
export const STAGE_LOGIN = 'STAGE_LOGIN'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_REG_ERROR = 'SET_REG_ERROR'

//mentors
export const LOAD_MENTORS = 'LOAD_MENTORS'
export const LOAD_USER = 'LOAD_USER'
export const SELECT_MENTOR = 'SELECT_MENTOR'
export const CHANGE_FILTER = 'CHANGE_FILTER'
export const UNSELECT_MENTOR = 'UNSELECT_MENTOR'

//messages
export const LOAD_MESSAGE_FOR_MENTOR = 'LOAD_MESSAGE_FOR_MENTOR'
export const LOAD_MESSAGE_FOR_THREAD = 'LOAD_MESSAGE_FOR_THREAD'
export const CREATE_NEW_MESSAGE_AND_THREAD = 'CREATE_NEW_MESSAGE_AND_THREAD'
export const CREATE_NEW_MESSAGE_ON_THREAD = 'CREATE_NEW_MESSAGE_ON_THREAD'
export const SELECT_THREAD = 'SELECT_THREAD'
export const UNSELECT_THREAD = 'UNSELECT_THREAD'
export const STAGE_MESSAGE = 'STAGE_MESSAGE'
export const LOAD_THREADS_FOR_USER = 'LOAD_THREADS_FOR_USER'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
